#!/usr/bin/env bash
# permanent redirection
site="/etc/nginx/sites-available/default"
pattern="server_name _;"


sed -i "/$pattern/a \
location = /redirect_me {\
\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\
\n\t}" $site


# restart server
sudo service nginx restart
