#!/usr/bin/env bash
# install load balancer and makes configurations

# prep os
apt -y update
apt -y upgrade

# install haproxy
apt -y install haproxy

# config
config="/etc/haproxy/haproxy.cfg"
echo -e "\nfrontend fontend\n\tbind *:80\n\tmode http\n\tdefault_backend servers\n\nbackend servers\n\tbalance roundrobin\n\tserver 498917-web-01 18.207.235.144:80 check\n\tserver 498917-web-02 54.209.218.24:80 check" >> $config

# restart haproxy
service haproxy restart
