#!/usr/bin/env bash
# download and execute mysql installation script

url="https://raw.githubusercontent.com/nuuxcode/alx-system_engineering-devops/master/scripts/mysql57"
file="0-mysql.bash"

sudo wget -O "$file" "$url" && sudo chmod +x "$file" && sudo ./"$file"
sudo rm *.deb
