#!/usr/bin/env bash
# classic fizzbuzz

for iter in {1..100}
do
    if [ $(( "$iter" % 5 )) == 0 ] && [ $(( "$iter" % 3 )) == 0 ]
    then
        echo "FizzBuzz"
    elif [ $(( "$iter" % 3 )) == 0 ]
    then
        echo "Fizz"
    elif [ $(( "$iter" % 5 )) == 0 ]
    then
        echo "Buzz"
    else
        echo ""$iter""
    fi
done
