#!/usr/bin/env bash
# more file stream cutting

IFS=":"

while read -r user pass uid gid desc home shell
do
    echo -n "The user $user is part of the $gid gang, lives in $home and rides $shell. "
    echo "${uid}'s place is protected by the passcode $pass, more info about the user here: $desc"
done < /etc/passwd
