#!/usr/bin/env bash

defaults="/etc/default/ufw"

# init firewall setup
sudo ufw default deny incoming

# allow connectivity
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https

# open port  8080
sudo ufw allow 8080/tcp

# listen only to port 80
sudo sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' "$defaults"
sudo ufw allow proto tcp from any port 8080 to any port 80
## sudo su -c 'ufw export save >> /etc/ufw/user.rules'

# restart
sudo ufw --force disable
sudo ufw --force enable
